#########################
#      database         #
#########################
namespace: jerney
config:
  name: jerney-config
  DB_HOST: ""
  DB_PORT: "5432"
  DB_NAME: ""
  DB_USER: ""
#########################
#      Backend          #
#########################
backend:
  namespace: jerney
  app_name: jerney-backend
  app_part: jerney
  app_component: backend
  replicaCount: 2
  containerport: 5000
  image_name: chimuanyavic7/jerney-backend
  image_tag: f28d3af
  type: ClusterIP
  service_port: 5000
  targetPort: 5000
#########################
#      frontend          #
#########################
frontend:
  namespace: jerney
  app_name: jerney-frontend
  app_part: jerney
  app_component: frontend
  replicaCount: 2
  containerport: 8080
  image_name: chimuanyavic7/jerney-frontend
  image_tag: f28d3af
  type: ClusterIP
  service_port: 80
  targetPort: 8080
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  scaleDown:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30
  scaleUp:
    stabilizationWindowSeconds: 30
    pods: 1
    periodSeconds: 30
hpa:
  name: attendance-app-hpa
  targetDeployment: attendance-app
